#!/bin/bash

prev=a

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur != $prev ]] 
		then
			if [[ $cur == "I watched Avengers: Endgame. Thanos d**s..." ]]
			then
				echo "Spoiler Alert!"
				break
			fi
			if [[ $cur != "I watched Avengers: Endgame. Thanos d**s..." ]]
			then
				echo $cur
				prev=$cur
			fi
		fi
	fi
done
